/* config.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "multiterm.h"
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _multi_term_config_unref0(var) ((var == NULL) ? NULL : (var = (multi_term_config_unref (var), NULL)))
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __g_list_free__multi_term_shell_config_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__multi_term_shell_config_free0_ (var), NULL)))
typedef struct _MultiTermParamSpecConfig MultiTermParamSpecConfig;

struct _MultiTermConfigPrivate {
	GKeyFile* kf;
	gchar* _filename;
};

struct _MultiTermParamSpecConfig {
	GParamSpec parent_instance;
};


static gpointer multi_term_config_parent_class = NULL;

#define MULTI_TERM_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MULTI_TERM_TYPE_CONFIG, MultiTermConfigPrivate))
enum  {
	MULTI_TERM_CONFIG_DUMMY_PROPERTY
};
static void _multi_term_shell_config_free0_ (gpointer var);
static void _g_list_free__multi_term_shell_config_free0_ (GList* self);
static void multi_term_config_finalize (MultiTermConfig* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _multi_term_config_ref0 (gpointer self) {
	return self ? multi_term_config_ref (self) : NULL;
}


void multi_term_shell_config_copy (const MultiTermShellConfig* self, MultiTermShellConfig* dest) {
	dest->section = g_strdup (self->section);
	dest->name = g_strdup (self->name);
	dest->command = g_strdup (self->command);
	dest->track_title = self->track_title;
	dest->cfg = _multi_term_config_ref0 (self->cfg);
}


void multi_term_shell_config_destroy (MultiTermShellConfig* self) {
	_g_free0 ((*self).section);
	_g_free0 ((*self).name);
	_g_free0 ((*self).command);
	_multi_term_config_unref0 ((*self).cfg);
}


MultiTermShellConfig* multi_term_shell_config_dup (const MultiTermShellConfig* self) {
	MultiTermShellConfig* dup;
	dup = g_new0 (MultiTermShellConfig, 1);
	multi_term_shell_config_copy (self, dup);
	return dup;
}


void multi_term_shell_config_free (MultiTermShellConfig* self) {
	multi_term_shell_config_destroy (self);
	g_free (self);
}


GType multi_term_shell_config_get_type (void) {
	static volatile gsize multi_term_shell_config_type_id__volatile = 0;
	if (g_once_init_enter (&multi_term_shell_config_type_id__volatile)) {
		GType multi_term_shell_config_type_id;
		multi_term_shell_config_type_id = g_boxed_type_register_static ("MultiTermShellConfig", (GBoxedCopyFunc) multi_term_shell_config_dup, (GBoxedFreeFunc) multi_term_shell_config_free);
		g_once_init_leave (&multi_term_shell_config_type_id__volatile, multi_term_shell_config_type_id);
	}
	return multi_term_shell_config_type_id__volatile;
}


MultiTermConfig* multi_term_config_construct (GType object_type, const gchar* filename) {
	MultiTermConfig* self = NULL;
	gchar* _tmp0_;
	GKeyFile* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (filename != NULL, NULL);
	self = (MultiTermConfig*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (filename);
	_g_free0 (self->priv->_filename);
	self->priv->_filename = _tmp0_;
	_tmp1_ = g_key_file_new ();
	_g_key_file_free0 (self->priv->kf);
	self->priv->kf = _tmp1_;
	g_key_file_load_from_file (self->priv->kf, self->priv->_filename, G_KEY_FILE_KEEP_COMMENTS | G_KEY_FILE_KEEP_TRANSLATIONS, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_KEY_FILE_ERROR) {
			goto __catch1_g_key_file_error;
		}
		if (_inner_error_->domain == G_FILE_ERROR) {
			goto __catch1_g_file_error;
		}
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	goto __finally1;
	__catch1_g_key_file_error:
	{
		GError * err;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:29: Unable to load config file %s: %s", self->priv->_filename, err->message);
		_g_error_free0 (err);
	}
	goto __finally1;
	__catch1_g_file_error:
	{
		GError * err;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:33: Unable to load config file %s: %s", self->priv->_filename, err->message);
		_g_error_free0 (err);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


MultiTermConfig* multi_term_config_new (const gchar* filename) {
	return multi_term_config_construct (MULTI_TERM_TYPE_CONFIG, filename);
}


void multi_term_config_store (MultiTermConfig* self) {
	gchar* _tmp0_ = NULL;
	gchar* data;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_key_file_to_data (self->priv->kf, NULL, NULL);
	data = _tmp0_;
	g_file_set_contents (self->priv->_filename, data, (gssize) (-1), &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_FILE_ERROR) {
			goto __catch2_g_file_error;
		}
		_g_free0 (data);
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	goto __finally2;
	__catch2_g_file_error:
	{
		GError * err;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:46: Unable to save config file %s: %s", self->priv->_filename, err->message);
		_g_error_free0 (err);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_free0 (data);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (data);
}


gchar* multi_term_config_get_background_color (MultiTermConfig* self) {
	gchar* result;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_key_file_get_string (self->priv->kf, "general", "bg_color", &_inner_error_);
	_tmp1_ = _tmp0_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_KEY_FILE_ERROR) {
			goto __catch3_g_key_file_error;
		}
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	result = _tmp1_;
	return result;
	goto __finally3;
	__catch3_g_key_file_error:
	{
		GError * err;
		gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:60: Error reading config value: %s", err->message);
		_tmp2_ = g_strdup ("#ffffff");
		result = _tmp2_;
		_g_error_free0 (err);
		return result;
	}
	__finally3:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void multi_term_config_set_background_color (MultiTermConfig* self, const gchar* value) {
	g_return_if_fail (self != NULL);
	g_key_file_set_string (self->priv->kf, "general", "bg_color", value);
}


gchar* multi_term_config_get_foreground_color (MultiTermConfig* self) {
	gchar* result;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_key_file_get_string (self->priv->kf, "general", "fg_color", &_inner_error_);
	_tmp1_ = _tmp0_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_KEY_FILE_ERROR) {
			goto __catch4_g_key_file_error;
		}
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	result = _tmp1_;
	return result;
	goto __finally4;
	__catch4_g_key_file_error:
	{
		GError * err;
		gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:77: Error reading config value: %s", err->message);
		_tmp2_ = g_strdup ("#000000");
		result = _tmp2_;
		_g_error_free0 (err);
		return result;
	}
	__finally4:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void multi_term_config_set_foreground_color (MultiTermConfig* self, const gchar* value) {
	g_return_if_fail (self != NULL);
	g_key_file_set_string (self->priv->kf, "general", "fg_color", value);
}


gchar* multi_term_config_get_font (MultiTermConfig* self) {
	gchar* result;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_key_file_get_string (self->priv->kf, "general", "font", &_inner_error_);
	_tmp1_ = _tmp0_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_KEY_FILE_ERROR) {
			goto __catch5_g_key_file_error;
		}
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	result = _tmp1_;
	return result;
	goto __finally5;
	__catch5_g_key_file_error:
	{
		GError * err;
		gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		g_warning ("config.vala:94: Error reading config value: %s", err->message);
		_tmp2_ = g_strdup ("Monospace 9");
		result = _tmp2_;
		_g_error_free0 (err);
		return result;
	}
	__finally5:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void multi_term_config_set_font (MultiTermConfig* self, const gchar* value) {
	g_return_if_fail (self != NULL);
	g_key_file_set_string (self->priv->kf, "general", "font", value);
}


const gchar* multi_term_config_get_filename (MultiTermConfig* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_filename;
	return result;
}


static void _multi_term_shell_config_free0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (multi_term_shell_config_free (var), NULL));
}


static void _g_list_free__multi_term_shell_config_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _multi_term_shell_config_free0_, NULL);
	g_list_free (self);
}


static gpointer _multi_term_shell_config_dup0 (gpointer self) {
	return self ? multi_term_shell_config_dup (self) : NULL;
}


GList* multi_term_config_get_shell_configs (MultiTermConfig* self) {
	GList* result;
	GList* list;
	gsize _tmp0_;
	gchar** _tmp1_ = NULL;
	gchar** sections;
	gint sections_length1;
	gint _sections_size_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	list = NULL;
	_tmp1_ = g_key_file_get_groups (self->priv->kf, &_tmp0_);
	sections = _tmp1_;
	sections_length1 = _tmp0_;
	_sections_size_ = _tmp0_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_;
				if (!_tmp2_) {
					i++;
				}
				_tmp2_ = FALSE;
				if (!(i < sections_length1)) {
					break;
				}
				_tmp3_ = g_str_has_prefix (sections[i], "shell=");
				if (_tmp3_) {
					MultiTermShellConfig sh = {0};
					MultiTermConfig* _tmp4_;
					gchar* _tmp5_;
					gchar* _tmp6_ = NULL;
					gchar* _tmp7_;
					gchar* _tmp8_ = NULL;
					gchar* _tmp9_;
					gboolean _tmp10_;
					gboolean _tmp11_;
					MultiTermShellConfig* _tmp12_;
					memset (&sh, 0, sizeof (MultiTermShellConfig));
					_tmp4_ = _multi_term_config_ref0 (self);
					_multi_term_config_unref0 (sh.cfg);
					sh.cfg = _tmp4_;
					_tmp5_ = g_strdup (sections[i]);
					_g_free0 (sh.section);
					sh.section = _tmp5_;
					_tmp6_ = g_key_file_get_string (self->priv->kf, sections[i], "name", &_inner_error_);
					_tmp7_ = _tmp6_;
					if (_inner_error_ != NULL) {
						multi_term_shell_config_destroy (&sh);
						if (_inner_error_->domain == G_KEY_FILE_ERROR) {
							goto __catch6_g_key_file_error;
						}
						multi_term_shell_config_destroy (&sh);
						sections = (_vala_array_free (sections, sections_length1, (GDestroyNotify) g_free), NULL);
						__g_list_free__multi_term_shell_config_free0_0 (list);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					_g_free0 (sh.name);
					sh.name = _tmp7_;
					_tmp8_ = g_key_file_get_string (self->priv->kf, sections[i], "command", &_inner_error_);
					_tmp9_ = _tmp8_;
					if (_inner_error_ != NULL) {
						multi_term_shell_config_destroy (&sh);
						if (_inner_error_->domain == G_KEY_FILE_ERROR) {
							goto __catch6_g_key_file_error;
						}
						multi_term_shell_config_destroy (&sh);
						sections = (_vala_array_free (sections, sections_length1, (GDestroyNotify) g_free), NULL);
						__g_list_free__multi_term_shell_config_free0_0 (list);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					_g_free0 (sh.command);
					sh.command = _tmp9_;
					_tmp10_ = g_key_file_get_boolean (self->priv->kf, sections[i], "track_title", &_inner_error_);
					_tmp11_ = _tmp10_;
					if (_inner_error_ != NULL) {
						multi_term_shell_config_destroy (&sh);
						if (_inner_error_->domain == G_KEY_FILE_ERROR) {
							goto __catch6_g_key_file_error;
						}
						multi_term_shell_config_destroy (&sh);
						sections = (_vala_array_free (sections, sections_length1, (GDestroyNotify) g_free), NULL);
						__g_list_free__multi_term_shell_config_free0_0 (list);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					sh.track_title = _tmp11_;
					_tmp12_ = _multi_term_shell_config_dup0 (&sh);
					list = g_list_append (list, _tmp12_);
					multi_term_shell_config_destroy (&sh);
					goto __finally6;
					__catch6_g_key_file_error:
					{
						GError * err;
						err = _inner_error_;
						_inner_error_ = NULL;
						g_warning ("config.vala:130: Error reading config value: %s", err->message);
						_g_error_free0 (err);
					}
					__finally6:
					if (_inner_error_ != NULL) {
						sections = (_vala_array_free (sections, sections_length1, (GDestroyNotify) g_free), NULL);
						__g_list_free__multi_term_shell_config_free0_0 (list);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
				}
			}
		}
	}
	result = list;
	sections = (_vala_array_free (sections, sections_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static void multi_term_value_config_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void multi_term_value_config_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		multi_term_config_unref (value->data[0].v_pointer);
	}
}


static void multi_term_value_config_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = multi_term_config_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer multi_term_value_config_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* multi_term_value_config_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		MultiTermConfig* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = multi_term_config_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* multi_term_value_config_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	MultiTermConfig** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = multi_term_config_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* multi_term_param_spec_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	MultiTermParamSpecConfig* spec;
	g_return_val_if_fail (g_type_is_a (object_type, MULTI_TERM_TYPE_CONFIG), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer multi_term_value_get_config (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MULTI_TERM_TYPE_CONFIG), NULL);
	return value->data[0].v_pointer;
}


void multi_term_value_set_config (GValue* value, gpointer v_object) {
	MultiTermConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MULTI_TERM_TYPE_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MULTI_TERM_TYPE_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		multi_term_config_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		multi_term_config_unref (old);
	}
}


void multi_term_value_take_config (GValue* value, gpointer v_object) {
	MultiTermConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MULTI_TERM_TYPE_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MULTI_TERM_TYPE_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		multi_term_config_unref (old);
	}
}


static void multi_term_config_class_init (MultiTermConfigClass * klass) {
	multi_term_config_parent_class = g_type_class_peek_parent (klass);
	MULTI_TERM_CONFIG_CLASS (klass)->finalize = multi_term_config_finalize;
	g_type_class_add_private (klass, sizeof (MultiTermConfigPrivate));
}


static void multi_term_config_instance_init (MultiTermConfig * self) {
	self->priv = MULTI_TERM_CONFIG_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void multi_term_config_finalize (MultiTermConfig* obj) {
	MultiTermConfig * self;
	self = MULTI_TERM_CONFIG (obj);
	_g_key_file_free0 (self->priv->kf);
	_g_free0 (self->priv->_filename);
}


GType multi_term_config_get_type (void) {
	static volatile gsize multi_term_config_type_id__volatile = 0;
	if (g_once_init_enter (&multi_term_config_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { multi_term_value_config_init, multi_term_value_config_free_value, multi_term_value_config_copy_value, multi_term_value_config_peek_pointer, "p", multi_term_value_config_collect_value, "p", multi_term_value_config_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (MultiTermConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) multi_term_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MultiTermConfig), 0, (GInstanceInitFunc) multi_term_config_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType multi_term_config_type_id;
		multi_term_config_type_id = g_type_register_fundamental (g_type_fundamental_next (), "MultiTermConfig", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&multi_term_config_type_id__volatile, multi_term_config_type_id);
	}
	return multi_term_config_type_id__volatile;
}


gpointer multi_term_config_ref (gpointer instance) {
	MultiTermConfig* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void multi_term_config_unref (gpointer instance) {
	MultiTermConfig* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MULTI_TERM_CONFIG_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



