/* iterminal.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from iterminal.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "multiterm.h"
#include <stdlib.h>
#include <string.h>






void multi_term_iterminal_run_command (MultiTermITerminal* self, const gchar* command) {
	MULTI_TERM_ITERMINAL_GET_INTERFACE (self)->run_command (self, command);
}


const gchar* multi_term_iterminal_get_tab_label_text (MultiTermITerminal* self) {
	return MULTI_TERM_ITERMINAL_GET_INTERFACE (self)->get_tab_label_text (self);
}


void multi_term_iterminal_set_tab_label_text (MultiTermITerminal* self, const gchar* value) {
	MULTI_TERM_ITERMINAL_GET_INTERFACE (self)->set_tab_label_text (self, value);
}


void multi_term_iterminal_set_background_color (MultiTermITerminal* self, const gchar* value) {
	MULTI_TERM_ITERMINAL_GET_INTERFACE (self)->set_background_color (self, value);
}


void multi_term_iterminal_set_foreground_color (MultiTermITerminal* self, const gchar* value) {
	MULTI_TERM_ITERMINAL_GET_INTERFACE (self)->set_foreground_color (self, value);
}


static void multi_term_iterminal_base_init (MultiTermITerminalIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_string ("tab-label-text", "tab-label-text", "tab-label-text", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
		g_object_interface_install_property (iface, g_param_spec_string ("background-color", "background-color", "background-color", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE));
		g_object_interface_install_property (iface, g_param_spec_string ("foreground-color", "foreground-color", "foreground-color", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE));
	}
}


GType multi_term_iterminal_get_type (void) {
	static volatile gsize multi_term_iterminal_type_id__volatile = 0;
	if (g_once_init_enter (&multi_term_iterminal_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MultiTermITerminalIface), (GBaseInitFunc) multi_term_iterminal_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType multi_term_iterminal_type_id;
		multi_term_iterminal_type_id = g_type_register_static (G_TYPE_INTERFACE, "MultiTermITerminal", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (multi_term_iterminal_type_id, GTK_TYPE_FRAME);
		g_once_init_leave (&multi_term_iterminal_type_id__volatile, multi_term_iterminal_type_id);
	}
	return multi_term_iterminal_type_id__volatile;
}



