/* plugin.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from plugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "multiterm.h"
#include <gtk/gtk.h>
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))


GeanyPlugin* geany_plugin = NULL;
GeanyData* geany_data = NULL;
GeanyFunctions* geany_functions = NULL;
MultiTermNotebook* nb = NULL;
extern GtkAlignment* align;
GtkAlignment* align = NULL;



static gint geany_vala_plugin_VERSION_CHECK (gint abi_version, gint api_required) {
	gint result = 0;
	if (abi_version != GEANY_ABI_VERSION) {
		result = -1;
		return result;
	}
	result = api_required;
	return result;
}


gint plugin_version_check (gint abi_version) {
	gint result = 0;
	gint _tmp0_;
	_tmp0_ = geany_vala_plugin_VERSION_CHECK (abi_version, 185);
	result = _tmp0_;
	return result;
}


static void geany_vala_plugin_SET_INFO (PluginInfo* self, const gchar* name, const gchar* description, const gchar* version, const gchar* author) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	self->name = name;
	self->description = description;
	self->version = version;
	self->author = author;
}


void plugin_set_info (PluginInfo* info) {
	g_return_if_fail (info != NULL);
	geany_vala_plugin_SET_INFO (info, "MultiTerm", "Multi-tabbed virtual terminal emulator.", "0.1", "Matthew Brush <mbrush@leftclick.ca>");
}


static GtkNotebook* geany_vala_plugin_main_widgets_get_message_window_notebook (GeanyMainWidgets* self) {
	GtkNotebook* result;
	GtkWidget* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->message_window_notebook;
	result = GTK_IS_NOTEBOOK (_tmp0_) ? ((GtkNotebook*) _tmp0_) : NULL;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void plugin_init (GeanyData* data) {
	GtkAlignment* _tmp0_ = NULL;
	MultiTermNotebook* _tmp1_ = NULL;
	MultiTermNotebook* _tmp2_;
	GtkNotebook* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_;
	GtkNotebook* _tmp6_ = NULL;
	GtkNotebook* _tmp7_;
	GtkNotebook* mwnb;
	gint _tmp8_;
	g_return_if_fail (data != NULL);
	plugin_module_make_resident (geany_plugin);
	_tmp0_ = (GtkAlignment*) gtk_alignment_new (0.5f, 0.5f, 1.0f, 1.0f);
	_g_object_unref0 (align);
	align = g_object_ref_sink (_tmp0_);
	_tmp1_ = multi_term_notebook_new ((guint) 1);
	_g_object_unref0 (nb);
	nb = g_object_ref_sink (_tmp1_);
	_tmp2_ = nb;
	gtk_container_add ((GtkContainer*) align, (GtkWidget*) (GTK_IS_NOTEBOOK (_tmp2_) ? ((GtkNotebook*) _tmp2_) : NULL));
	_tmp3_ = geany_vala_plugin_main_widgets_get_message_window_notebook (data->main_widgets);
	_tmp4_ = (GtkLabel*) gtk_label_new ("MultiTerm");
	_tmp5_ = g_object_ref_sink (_tmp4_);
	gtk_notebook_append_page (_tmp3_, (GtkWidget*) align, (GtkWidget*) _tmp5_);
	_g_object_unref0 (_tmp5_);
	gtk_widget_show_all ((GtkWidget*) align);
	_tmp6_ = geany_vala_plugin_main_widgets_get_message_window_notebook (data->main_widgets);
	_tmp7_ = _g_object_ref0 (GTK_NOTEBOOK (_tmp6_));
	mwnb = _tmp7_;
	_tmp8_ = gtk_notebook_page_num (mwnb, (GtkWidget*) align);
	gtk_notebook_set_current_page (mwnb, _tmp8_);
	_g_object_unref0 (mwnb);
}


void plugin_cleanup (void) {
	gtk_object_destroy ((GtkObject*) align);
}



