/* tab-label.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from tab-label.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "multiterm.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MultiTermTabLabelPrivate {
	GtkButton* btn;
};


static gpointer multi_term_tab_label_parent_class = NULL;

#define MULTI_TERM_TAB_LABEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MULTI_TERM_TYPE_TAB_LABEL, MultiTermTabLabelPrivate))
enum  {
	MULTI_TERM_TAB_LABEL_DUMMY_PROPERTY,
	MULTI_TERM_TAB_LABEL_TEXT,
	MULTI_TERM_TAB_LABEL_BUTTON
};
static void multi_term_tab_label_on_button_clicked (MultiTermTabLabel* self);
static void multi_term_tab_label_on_button_style_set (MultiTermTabLabel* self, GtkStyle* previous_style);
static void _multi_term_tab_label_on_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _multi_term_tab_label_on_button_style_set_gtk_widget_style_set (GtkWidget* _sender, GtkStyle* previous_style, gpointer self);
static void multi_term_tab_label_finalize (GObject* obj);
static void _vala_multi_term_tab_label_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_multi_term_tab_label_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void multi_term_tab_label_on_button_clicked (MultiTermTabLabel* self) {
	gconstpointer _tmp0_ = NULL;
	MultiTermTerminal* _tmp1_;
	MultiTermTerminal* term;
	GtkWidget* _tmp2_ = NULL;
	MultiTermNotebook* _tmp3_;
	MultiTermNotebook* nb;
	gint _tmp4_;
	gint page_num;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_object_get_data ((GObject*) self, "terminal");
	_tmp1_ = _g_object_ref0 ((MultiTermTerminal*) _tmp0_);
	term = _tmp1_;
	_tmp2_ = gtk_widget_get_parent ((GtkWidget*) term);
	_tmp3_ = _g_object_ref0 (MULTI_TERM_NOTEBOOK (_tmp2_));
	nb = _tmp3_;
	_tmp4_ = gtk_notebook_page_num ((GtkNotebook*) nb, (GtkWidget*) term);
	page_num = _tmp4_;
	g_signal_emit_by_name (self, "close-clicked", page_num);
	_g_object_unref0 (nb);
	_g_object_unref0 (term);
}


static void multi_term_tab_label_on_button_style_set (MultiTermTabLabel* self, GtkStyle* previous_style) {
	gint w = 0;
	gint h = 0;
	GtkSettings* _tmp0_ = NULL;
	gint _tmp1_;
	gint _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_settings ((GtkWidget*) self->priv->btn);
	gtk_icon_size_lookup_for_settings (_tmp0_, GTK_ICON_SIZE_MENU, &_tmp1_, &_tmp2_);
	w = _tmp1_;
	h = _tmp2_;
	gtk_widget_set_size_request ((GtkWidget*) self->priv->btn, w + 2, h + 2);
}


static void _multi_term_tab_label_on_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	multi_term_tab_label_on_button_clicked (self);
}


static void _multi_term_tab_label_on_button_style_set_gtk_widget_style_set (GtkWidget* _sender, GtkStyle* previous_style, gpointer self) {
	multi_term_tab_label_on_button_style_set (self, previous_style);
}


MultiTermTabLabel* multi_term_tab_label_construct (GType object_type, const gchar* text) {
	MultiTermTabLabel * self = NULL;
	GtkImage* img = NULL;
	GtkLabel* _tmp0_ = NULL;
	GtkImage* _tmp1_ = NULL;
	GtkRcStyle* _tmp2_ = NULL;
	GtkRcStyle* style;
	GtkButton* _tmp3_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	self = (MultiTermTabLabel*) g_object_new (object_type, "homogeneous", FALSE, "spacing", 2, NULL);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 0);
	_tmp0_ = (GtkLabel*) gtk_label_new (text);
	_g_object_unref0 (self->label);
	self->label = g_object_ref_sink (_tmp0_);
	gtk_misc_set_alignment ((GtkMisc*) self->label, 0.0f, 0.5f);
	gtk_label_set_ellipsize (self->label, PANGO_ELLIPSIZE_END);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->label, TRUE, TRUE, (guint) 0);
	_tmp1_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_CLOSE, GTK_ICON_SIZE_MENU);
	_g_object_unref0 (img);
	img = g_object_ref_sink (_tmp1_);
	_tmp2_ = gtk_rc_style_new ();
	style = _tmp2_;
	style->xthickness = 0;
	style->ythickness = 0;
	_tmp3_ = (GtkButton*) gtk_button_new ();
	_g_object_unref0 (self->priv->btn);
	self->priv->btn = g_object_ref_sink (_tmp3_);
	gtk_widget_modify_style ((GtkWidget*) self->priv->btn, style);
	gtk_container_add ((GtkContainer*) self->priv->btn, (GtkWidget*) img);
	gtk_widget_set_tooltip_text ((GtkWidget*) self->priv->btn, "Close terminal");
	g_signal_connect_object (self->priv->btn, "clicked", (GCallback) _multi_term_tab_label_on_button_clicked_gtk_button_clicked, self, 0);
	gtk_button_set_relief (self->priv->btn, GTK_RELIEF_NONE);
	gtk_button_set_focus_on_click (self->priv->btn, FALSE);
	g_signal_connect_object ((GtkWidget*) self->priv->btn, "style-set", (GCallback) _multi_term_tab_label_on_button_style_set_gtk_widget_style_set, self, 0);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->btn, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (style);
	_g_object_unref0 (img);
	return self;
}


MultiTermTabLabel* multi_term_tab_label_new (const gchar* text) {
	return multi_term_tab_label_construct (MULTI_TERM_TYPE_TAB_LABEL, text);
}


const gchar* multi_term_tab_label_get_text (MultiTermTabLabel* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_label_get_label (self->label);
	result = _tmp0_;
	return result;
}


void multi_term_tab_label_set_text (MultiTermTabLabel* self, const gchar* value) {
	g_return_if_fail (self != NULL);
	gtk_label_set_label (self->label, value);
	g_object_notify ((GObject *) self, "text");
}


GtkButton* multi_term_tab_label_get_button (MultiTermTabLabel* self) {
	GtkButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->btn;
	return result;
}


static void multi_term_tab_label_class_init (MultiTermTabLabelClass * klass) {
	multi_term_tab_label_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MultiTermTabLabelPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_multi_term_tab_label_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_multi_term_tab_label_set_property;
	G_OBJECT_CLASS (klass)->finalize = multi_term_tab_label_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MULTI_TERM_TAB_LABEL_TEXT, g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MULTI_TERM_TAB_LABEL_BUTTON, g_param_spec_object ("button", "button", "button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("close_clicked", MULTI_TERM_TYPE_TAB_LABEL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
}


static void multi_term_tab_label_instance_init (MultiTermTabLabel * self) {
	self->priv = MULTI_TERM_TAB_LABEL_GET_PRIVATE (self);
}


static void multi_term_tab_label_finalize (GObject* obj) {
	MultiTermTabLabel * self;
	self = MULTI_TERM_TAB_LABEL (obj);
	_g_object_unref0 (self->priv->btn);
	_g_object_unref0 (self->label);
	G_OBJECT_CLASS (multi_term_tab_label_parent_class)->finalize (obj);
}


GType multi_term_tab_label_get_type (void) {
	static volatile gsize multi_term_tab_label_type_id__volatile = 0;
	if (g_once_init_enter (&multi_term_tab_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MultiTermTabLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) multi_term_tab_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MultiTermTabLabel), 0, (GInstanceInitFunc) multi_term_tab_label_instance_init, NULL };
		GType multi_term_tab_label_type_id;
		multi_term_tab_label_type_id = g_type_register_static (GTK_TYPE_HBOX, "MultiTermTabLabel", &g_define_type_info, 0);
		g_once_init_leave (&multi_term_tab_label_type_id__volatile, multi_term_tab_label_type_id);
	}
	return multi_term_tab_label_type_id__volatile;
}


static void _vala_multi_term_tab_label_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MultiTermTabLabel * self;
	self = MULTI_TERM_TAB_LABEL (object);
	switch (property_id) {
		case MULTI_TERM_TAB_LABEL_TEXT:
		g_value_set_string (value, multi_term_tab_label_get_text (self));
		break;
		case MULTI_TERM_TAB_LABEL_BUTTON:
		g_value_set_object (value, multi_term_tab_label_get_button (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_multi_term_tab_label_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MultiTermTabLabel * self;
	self = MULTI_TERM_TAB_LABEL (object);
	switch (property_id) {
		case MULTI_TERM_TAB_LABEL_TEXT:
		multi_term_tab_label_set_text (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



